version: 0.0
os: linux

files:
  - source: https://github.com/kantu18/AWS_FoodAPP/tree/main/scripts
    destination: /home/ec2-user/server

hooks:
  BeforeInstall:
    - location: scripts/server_clear.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/fix_privileges.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: ec2-user
