version: 0.0
os: linux

files:
  - source: /FoodFrenzy-main/scripts/*
    destination: /home/ec2-user/server

permissions:
  - object: /home/ec2-user/server
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  BeforeInstall:
    - location: /home/ec2-user/server/scripts/server_clear.sh
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: /home/ec2-user/server/scripts/fix_privileges.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: /home/ec2-user/server/scripts/server_start.sh
      timeout: 20
      runas: ec2-user
  ApplicationStop:
    - location: /home/ec2-user/server/scripts/server_stop.sh
      timeout: 20
      runas: ec2-user
